name: main
permissions: write-all
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  validate:
    name: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: "actions/checkout@v5"
        with:
          fetch-depth: 0
      - name: Setup Mise
        uses: "jdx/mise-action@v3"
        with:
          install: true
          experimental: true
      - name: Init terraform
        run: terraform init
      - name: Validate terraform
        run: terraform validate
  release:
    needs:
      - validate
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup Mise
        uses: "jdx/mise-action@v3"
        with:
          install: true
          experimental: true
      - name: Install dependencies
        run: |
          npm install -D '@semantic-release/commit-analyzer' \
          '@semantic-release/release-notes-generator' \
          '@semantic-release/changelog' \
          'semantic-release-license' \
          '@semantic-release/github'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
